repo_name: "finapp"
description: "This repo was created entirely via Terraform and GitHub Apps."
enable_branch_protection: true
# update_branch: "chore/vending-updates" # Uncomment to create a dedicated update branch when branch protection is enabled
