repo_name: "add-workflow-to-repo"
description: "This repo was created entirely via Terraform and GitHub Apps."
additional_topics:
  - terraform
  - testing
enable_branch_protection: true
# update_branch: "chore/vending-updates" # Uncomment to create a dedicated update branch when branch protection is enabled
